spring.application.name=backend
server.port=8080

# Temporarily disable DB so we can test hello endpoint
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
